import type { ReviewItem } from './types';

export const mockReviewItems: ReviewItem[] = [
  {
    id: 'G12-001-v1',
    variant_id: 'G12-001-v1',
    task: {
      task_id: 'G12-001',
      task_type: 'TT_CHOOSE_CORRECT',
      title: 'Зөв үгийг сонго',
      prompt_text: 'Дараах үгийг зөв бичнэ үү: тогоо',
      correct_answer: 'тогоо',
      options: { expected_answers: ['тогоо', 'тогоо', 'тогоо', 'тогоо'] },
      audio_url: null,
      image_url: null,
      primary_skill: 'S1',
      secondary_skill: null,
      level_target: 'M1',
      error_targets: ['A'],
      grade_band: ['G1', 'G2'],
      difficulty: 2,
      estimated_time_seconds: 30,
      lesson_slot_fit: 'CORE',
      feedback_text: 'Зөв! "Тогоо" гэж зөв бичлээ.',
    },
    ai_review_severity: 'ok',
    ai_review_issues: [],
    ai_fix_suggestion: null,
    status: 'ai_passed',
    created_at: '2026-04-28T08:00:00.000Z',
    reviewer_notes: null,
    flag_reason: null,
    revision_reason: null,
    rejection_reason: null,
  },
  {
    id: 'G12-007-v1',
    variant_id: 'G12-007-v1',
    task: {
      task_id: 'G12-007',
      task_type: 'TT_CHOOSE_CORRECT',
      title: 'Зөв бичлэг сонго',
      prompt_text: 'Аль нь зөв бичсэн бэ?',
      correct_answer: 'сүү',
      options: { expected_answers: ['сүү', 'суу', 'сүу', 'суү'] },
      audio_url: null,
      image_url: null,
      primary_skill: 'S3',
      secondary_skill: null,
      level_target: 'M2',
      error_targets: ['C1', 'C2'],
      grade_band: ['G1', 'G2'],
      difficulty: 3,
      estimated_time_seconds: 30,
      lesson_slot_fit: 'CORE',
      feedback_text: 'Зөв! Урт "үү" авиа зөв бичигдэв.',
    },
    ai_review_severity: 'ok',
    ai_review_issues: [],
    ai_fix_suggestion: null,
    status: 'ai_passed',
    created_at: '2026-04-28T09:15:00.000Z',
    reviewer_notes: null,
    flag_reason: null,
    revision_reason: null,
    rejection_reason: null,
  },
  {
    id: 'G24-012-v1',
    variant_id: 'G24-012-v1',
    task: {
      task_id: 'G24-012',
      task_type: 'TT_CHOOSE_CORRECT',
      title: 'Зөв хариуг сонго',
      prompt_text: 'Зөв хариуг сонгоно уу: шувуу',
      correct_answer: 'шувуу',
      options: { expected_answers: ['шувуу', 'шувуу', 'шувуу', 'шувуу'] },
      audio_url: null,
      image_url: null,
      primary_skill: 'S2',
      secondary_skill: null,
      level_target: 'M1',
      error_targets: ['B'],
      grade_band: ['G3', 'G4'],
      difficulty: 2,
      estimated_time_seconds: 30,
      lesson_slot_fit: 'CORE',
      feedback_text: 'Зөв бичлээ!',
    },
    ai_review_severity: 'minor',
    ai_review_issues: ['B'],
    ai_fix_suggestion: null,
    status: 'ai_flagged',
    created_at: '2026-04-28T10:30:00.000Z',
    reviewer_notes: null,
    flag_reason: null,
    revision_reason: null,
    rejection_reason: null,
  },
  {
    id: 'G24-019-v1',
    variant_id: 'G24-019-v1',
    task: {
      task_id: 'G24-019',
      task_type: 'TT_WORD_SET_DICTATION',
      title: 'Сонсоод бичээрэй',
      prompt_text: 'Сонссон үгс болон өгүүлбэрийг бичээрэй.',
      correct_answer: 'сүү;ном;гал',
      options: {
        audio_text: 'сүү, ном, гал',
        word_count: 3,
        expected_answers: ['сүү', 'ном', 'гал'],
        allow_partial: true,
      },
      audio_url: null,
      image_url: null,
      primary_skill: 'S7',
      secondary_skill: null,
      level_target: 'M2',
      error_targets: ['A', 'C1'],
      grade_band: ['G3', 'G4'],
      difficulty: 3,
      estimated_time_seconds: 45,
      lesson_slot_fit: 'END',
      feedback_text: 'Сонссон үгсийг зөв бичлээ үү?',
    },
    ai_review_severity: 'minor',
    ai_review_issues: ['A', 'C1'],
    ai_fix_suggestion: null,
    status: 'ai_flagged',
    created_at: '2026-04-29T07:00:00.000Z',
    reviewer_notes: null,
    flag_reason: null,
    revision_reason: null,
    rejection_reason: null,
  },
  {
    id: 'G12-003-v1',
    variant_id: 'G12-003-v1',
    task: {
      task_id: 'G12-003',
      task_type: 'TT_WORD_SET_DICTATION',
      title: 'Сонсоод бичээрэй',
      prompt_text: 'Сонсоод зөв үгийг бичнэ үү.',
      correct_answer: 'тогоо',
      options: {
        audio_text: 'тогоо',
        word_count: 1,
        expected_answers: ['тогоо'],
        allow_partial: false,
      },
      audio_url: null,
      image_url: null,
      primary_skill: 'S1',
      secondary_skill: null,
      level_target: 'M0',
      error_targets: [],
      grade_band: ['G1', 'G2'],
      difficulty: 1,
      estimated_time_seconds: 20,
      lesson_slot_fit: 'END',
      feedback_text: 'Гайхалтай! Зөв сонссон.',
    },
    ai_review_severity: null,
    ai_review_issues: [],
    ai_fix_suggestion: null,
    status: 'pending',
    created_at: '2026-04-30T06:00:00.000Z',
    reviewer_notes: null,
    flag_reason: null,
    revision_reason: null,
    rejection_reason: null,
  },
];
